apiVersion: v1
kind: Template
metadata:
  name: container-first-service-template
  labels:
    name: first-service
  annotations:
    description: Template for the Container first-service
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: first-service
        service: ${SERVICE_NAME}
      name: ${SERVICE_NAME}
      annotations:
        description: "The Container first-service service"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
          protocol: TCP  
      selector:
        name: ${SERVICE_NAME}
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        name: first-service
      name: ${SERVICE_NAME}
      annotations:
        description: "The route to expose the Container first-service's 8080 port"
    spec:
      host: ${SERVICE_NAME}-${NAMESPACE}.${CLUSTER_URL}
      to:
        kind: Service
        name: ${SERVICE_NAME}
      port:
        targetPort: 8080-tcp
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: first-service-simple-config-map
    data:
      TEST_CONF_MAP1: ${TEST_CONF_MAP1}
      TEST_CONF_MAP2: ${TEST_CONF_MAP2}
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: fist-service-settings-file
    data:
      first-service-settings.json: |-
        {
          "NAME": "${SERVICE_NAME}",
          "Description": "${SERVICE_NAME}"
        }
  - kind: Secret
    apiVersion: v1
    metadata:
      name: first-service-secrets
    data:
      TEST_SECRET_CONF_MAP1: "${TEST_SECRET_CONF_MAP1}"
      TEST_SECRET_CONF_MAP2: "${TEST_SECRET_CONF_MAP2}"
    type: Opaque
  - kind: Secret
    apiVersion: v1
    metadata:
      name: first-service-secret-file
    data:
      secret.txt: SGVsbG8gZnJvbSBTZWNyZXQtZmlsZQ==
    type: Opaque
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: first-service-data
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Mi
      volumeName: pv0028
      volumeMode: Filesystem
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${SERVICE_NAME}
      labels:
        name: first-service
      annotations:
        description: "The Container first-service deployment configuration"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 18000
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${SERVICE_NAME}
            from:
              kind: ImageStreamTag
              name: "${SERVICE_NAME}:${VERSION}"
      replicas: 2
      selector:
        name: ${SERVICE_NAME}
        deploymentconfig: ${SERVICE_NAME}
      template:
        metadata:
          labels:
            name: first-service
            deploymentconfig: ${SERVICE_NAME}
        spec:
          volumes:
            - name: first-service-settings-volume
              configMap:
                name: fist-service-settings-file
                defaultMode: 420
            - name: first-service-secret-volume
              secret:
                secretName: first-service-secret-file
                defaultMode: 420
            - name: first-service-data
              persistentVolumeClaim:
                claimName: first-service-data
          containers:
            - name: ${SERVICE_NAME}
              image: "${NAMESPACE}/${SERVICE_NAME}:${VERSION}"
              imagePullPolicy: Always
              env:
                - name: TEST_ENV_VARIABLE
                  value: ${TEST_ENV_VARIABLE}
                - name: TEST_CONF_MAP1
                  valueFrom:
                    configMapKeyRef:
                      name: first-service-simple-config-map
                      key: TEST_CONF_MAP1
                - name: TEST_CONF_MAP2
                  valueFrom:
                    configMapKeyRef:
                      name: first-service-simple-config-map
                      key: TEST_CONF_MAP2
                - name: TEST_SECRET_CONF_MAP1
                  valueFrom:
                    secretKeyRef:
                      name: first-service-secrets
                      key: TEST_SECRET_CONF_MAP1
                - name: TEST_SECRET_CONF_MAP2
                  valueFrom:
                    secretKeyRef:
                      name: first-service-secrets
                      key: TEST_SECRET_CONF_MAP2
#              resources:
#                limits:
#                  memory: 512Mi
#              readinessProbe:
#                httpGet:
#                  path: /first-service/healthy
#                  port: 8080
#                  scheme: HTTP
#                initialDelaySeconds: 60
#                timeoutSeconds: 30
#                periodSeconds: 300
#                successThreshold: 1
#                failureThreshold: 3
#              livenessProbe:
#                httpGet:
#                  path: /first-service/healthy
#                  port: 8080
#                  scheme: HTTP
#                initialDelaySeconds: 60
#                timeoutSeconds: 30
#                periodSeconds: 360
#                successThreshold: 1
#                failureThreshold: 3
              volumeMounts:
                - name: first-service-settings-volume
                  mountPath: /application/settings
                - name: first-service-secret-volume
                  mountPath: /application/secret
                - name: first-service-data
                  mountPath: /application/media
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 60
        test: false
      status: {}
parameters:
  - name: CLUSTER_URL
    description: "Cluster url"
    value: apps-crc.testing
  - name: NAMESPACE
    description: "Name space"
    value: distributed-systems
  - name: SERVICE_NAME
    description: "Service name"
    value: first-service
  - name: VERSION
    description: "Version of first-service"
    required: true
  - name: TEST_ENV_VARIABLE
    description: Test environment variable
    required: true
  - name: TEST_CONF_MAP1
  - name: TEST_CONF_MAP2
  - name: TEST_SECRET_CONF_MAP1
  - name: TEST_SECRET_CONF_MAP2