apiVersion: v1
kind: Template
metadata:
  name: container-first-service-template
  labels:
    name: first-service
  annotations:
    description: Template for the Container first-service
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        description: Container first-service image stream
      labels:
        name: first-service
      name: first-service
    spec:
      tags:
      - annotations:
        from:
          kind: DockerImage
          name: olgafedorova/first-service:latest
        name: latest
        importPolicy: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: first-service
        service: first-service
      name: first-service
      annotations:
        description: "The Container first-service service"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
          protocol: TCP  
      selector:
        name: first-service
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        name: first-service
      name: first-service
      annotations:
        description: "The route to expose the Container first-service's 8080 port"
    spec:
      host: first-service-distributed-systems.192.168.64.2.nip.io
      to:
        kind: Service
        name: first-service
      port:
        targetPort: 8080-tcp
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: first-service
      labels:
        name: first-service
      annotations:
        description: "The Container first-service deployment configuration"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 18000
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - first-service
            from:
              kind: ImageStreamTag
              name: "first-service:latest"
      replicas: 1
      selector:
        name: first-service
        deploymentconfig: first-service
      template:
        metadata:
          labels:
            name: first-service
            deploymentconfig: first-service
        spec:
          containers:
            - name: first-service
              image: "olgafedorova/first-service:latest"
              imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 60
        test: false
      status: {}