apiVersion: v1
kind: Template
metadata:
  name: container-jaeger-template
  labels:
    name: jaeger
  annotations:
    description: Template for the Container Jaeger
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        description: Container Jaeger image stream
      labels:
        name: jaeger
      name: jaeger
    spec:
      tags:
      - annotations:
        from:
          kind: DockerImage
          name: jaegertracing/all-in-one:1.18.1
        name: 1.18.1
        importPolicy: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: jaeger
        service: jaeger
      name: jaeger
      annotations:
        description: "The Container Jaeger service"
    spec:
      ports:
        - name: 5775-udp
          port: 5775
          targetPort: 5775
          protocol: UDP
        - name: 5778-tcp
          port: 5778
          targetPort: 5778
          protocol: TCP
        - name: 6831-udp
          port: 6831
          targetPort: 6831
          protocol: UDP
        - name: 6832-udp
          port: 6832
          targetPort: 6832
          protocol: UDP
        - name: 14250-tcp
          port: 14250
          targetPort: 14250
          protocol: TCP
        - name: 14268-tcp
          port: 14268
          targetPort: 14268
          protocol: TCP     
        - name: 16686-tcp
          port: 16686
          targetPort: 16686
          protocol: TCP
        - name: 9411-tcp
          port: 9411
          targetPort: 9411
          protocol: TCP
      selector:
        name: jaeger
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        name: jaeger
      name: jaeger
      annotations:
        description: "The route to expose the Container Jaeger's 16686 port"
    spec:
      host: jaeger-distributed-systems.192.168.64.2.nip.io
      to:
        kind: Service
        name: jaeger
      port:
        targetPort: 16686-tcp
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: jaeger
      labels:
        name: jaeger
      annotations:
        description: "The Container Jaeger deployment configuration"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 18000
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - jaeger
            from:
              kind: ImageStreamTag
              name: "jaeger:1.18.1"
      replicas: 1
      selector:
        name: jaeger
        deploymentconfig: jaeger
      template:
        metadata:
          labels:
            name: jaeger
            deploymentconfig: jaeger
        spec:
          containers:
            - name: jaeger
              image: "jaegertracing/all-in-one:1.18.1"
              imagePullPolicy: Always
              env:
                - name: COLLECTOR_ZIPKIN_HTTP_PORT
                  value: '9411'
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 60
        test: false
      status: {}