apiVersion: v1
kind: Template
metadata:
  name: container-second-service-with-sleuth-template
  labels:
    name: second-service-with-sleuth
  annotations:
    description: Template for the Container second-service-with-sleuth
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        description: Container second-service-with-sleuth image stream
      labels:
        name: second-service-with-sleuth
      name: second-service-with-sleuth
    spec:
      tags:
      - annotations:
        from:
          kind: DockerImage
          name: olgafedorova/second-service-with-sleuth:latest
        name: latest
        importPolicy: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: second-service-with-sleuth
        service: second-service-with-sleuth
      name: second-service-with-sleuth
      annotations:
        description: "The Container second-service-with-sleuth service"
    spec:
      ports:
        - name: 8084-tcp
          port: 8084
          targetPort: 8084
          protocol: TCP  
      selector:
        name: second-service-with-sleuth
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        name: second-service-with-sleuth
      name: second-service-with-sleuth
      annotations:
        description: "The route to expose the Container second-service-with-sleuth's 8084 port"
    spec:
      host: second-service-with-sleuth-distributed-systems.192.168.64.2.nip.io
      to:
        kind: Service
        name: second-service-with-sleuth
      port:
        targetPort: 8084-tcp
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: second-service-with-sleuth
      labels:
        name: second-service-with-sleuth
      annotations:
        description: "The Container second-service-with-sleuth deployment configuration"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 18000
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - second-service-with-sleuth
            from:
              kind: ImageStreamTag
              name: "second-service-with-sleuth:latest"
      replicas: 1
      selector:
        name: second-service-with-sleuth
        deploymentconfig: second-service-with-sleuth
      template:
        metadata:
          labels:
            name: second-service-with-sleuth
            deploymentconfig: second-service-with-sleuth
        spec:
          containers:
            - name: second-service-with-sleuth
              image: "olgafedorova/second-service-with-sleuth:latest"
              imagePullPolicy: Always
          ports:
            - containerPort: 8084
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 60
        test: false
      status: {}