version: "3"
services:
  redis:
    image: library/redis:6.0
    ports:
    - 6379:6379
    networks:
      - distributed
  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: on-failure
    networks:
      - distributed
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - distributed
  kibana:
    image: kibana:7.2.0
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - distributed
  fluentd:
    build: ./fluentd
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - distributed
  first-service:
    image: olgafedorova/first-service
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    links:
      - jaeger
      - redis
      - fluentd
    depends_on:
      - jaeger
      - redis
    ports:
      - 8080:8080
    networks:
      - distributed
  first-service-with-sleuth:
    image: olgafedorova/first-service-with-sleuth
    links:
      - jaeger
    depends_on:
      - jaeger
    ports:
      - 8082:8082
    networks:
      - distributed
  second-service:
    image: olgafedorova/second-service
    links:
      - jaeger
      - first-service
    depends_on:
      - jaeger
      - first-service
    ports:
      - 8081:8081
    networks:
      - distributed
  second-service-with-sleuth:
    image: olgafedorova/second-service-with-sleuth
    links:
      - jaeger
      - first-service-with-sleuth
    depends_on:
      - jaeger
      - first-service-with-sleuth
    ports:
      - 8084:8084
    networks:
      - distributed
networks:
  distributed:
    driver: bridge