version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    ports:
      - 6831:6831/udp
      - 16686:16686
    restart: on-failure
    networks:
      - distributed
  first-service:
    image: olgafedorova/first-service
    links:
      - jaeger
    depends_on:
      - jaeger
    ports:
      - 8080:8080
    networks:
      - distributed
  second-service:
    image: olgafedorova/second-service
    links:
      - jaeger
      - first-service
    depends_on:
      - jaeger
      - first-service
    ports:
      - 8081:8081
    networks:
      - distributed
networks:
  distributed:
    driver: bridge