server:
  port: 8080
  servlet:
    context-path: /first-service

opentracing:
  jaeger:
    service-name: first-service
    enabled: true
    udp-sender:
      host: localhost
      port: 6831
spring:
  application:
    name: first-service
  redis:
    host: localhost
    port: 6379

test.env.variables: ${TEST_ENV_VARIABLE}
test.conf.map1: ${TEST_CONF_MAP1}
test.conf.map2: ${TEST_CONF_MAP2}
test.secret.conf.map1: ${TEST_SECRET_CONF_MAP1}
test.secret.conf.map2: ${TEST_SECRET_CONF_MAP2}

file.path.settings: /application/settings
file.path.secret: /application/secret
file.path.media: /application/media