server:
  port: 8080
  servlet:
    context-path: /first-service

opentracing:
  jaeger:
    service-name: first-service
    enabled: true
    udp-sender:
      host: localhost
      port: 6831
spring:
  application:
    name: first-service
  redis:
    host: localhost
    port: 6379
