server:
  port: 8081
  servlet:
    context-path: /second-service

opentracing:
  jaeger:
    service-name: second-service
    enabled: true
    udp-sender:
      host: localhost
      port: 6831


first-service:
  url: http://localhost:8080/first-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
